### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by Ramon-T** [numinix/tableau#10]
Hello,

After following the directions exactly and seeking answers from the support forum at zen-cart, my twitter feed is still directed to numinix.  http://metaldetectingandotherstuffidig.us/

Can you help me figure out why?  Here are the directions I followed:

Twitter Feed Section Title: This is the title for the Twitter Feed section.
Twitter Handle: This is your username at twitter.
Additional Twitter Information: to fully configure the Twitter section you need to open the following file YOUR_CATALOG => twitter => index.php. The following fields need to be customized:
// Your Twitter App Consumer Key
private $consumer_key = 'YOUR CODE HERE';

// Your Twitter App Consumer Secret
private $consumer_secret = 'YOUR CODE HERE';

// Your Twitter App Access Token
private $user_token = 'YOUR CODE HERE';

// Your Twitter App Access Token Secret
private $user_secret = 'YOUR CODE HERE';
        
To create those you need to create consumer and secret keys which you can get from dev.twitter.com/apps.

and:

Changed from:
// Path to writable cache directory
private $cache_dir = './';

Changed to:
// Path to writable cache directory
private $cache_dir = '/home/metaldf1/public_html/cache/';

To find the correct path refer to "DIR_FS_SQL_CACHE" in your /includes/configure.php

**Comment by jono-numinix** [comment]
Hello -

Sorry you are having this issue. A few questions for you:

1. What version of Tableau are you running?
2. Did you get the appropriate codes inside dev.twittee.com and replace them in that file as the directions say to?
3. When you go to the template configuration what dors the Twitter handle say?

**Comment by Ramon-T** [comment]
Hi Jono,

Thanks for the response.  I am running 1.3.2. on zencart 1.5.3.   All of the twitter codes were triple checked.  In configuration it has my twitter handle, which is displayed correctly on the site.  I'm at a loss.  I can't find where the twitter feed points to numinix?

Thank you,

Ray

**Comment by jono-numinix** [comment]
Hello -

Alright thanks for that. Can you please also confirm that you have this file inside Tableau? YOUR_CATALOG/includes/templates/tableau/jscript/jquery_tweet_addon.php and if so can you please let me know what it says for the username?

Thanks!

**Comment by jono-numinix** [comment]
Also it would be best if you upgrade to 1.3.4 on tableau as that is the latest version and some bugs have been fixed since then.

**Comment by Ramon-T** [comment]
It says "numinix". I guess I should add my handle?  Also, I tried to upgrade, but I am illiterate when it comes to uploading templates.  It took me a month and ended up paying someone $50 to upload Tableau!  lol.

**Comment by Ramon-T** [comment]
It worked.  Thank you so much for your help.  I really appreciate it!

Ray

**Comment by jono-numinix** [comment]
Hey -

Glad you were able to fix your issue. When you get a chance to upgrade in the future, we will be happy to help.

Thanks!

**Comment by Ramon-T** [comment]
One more thing.  My feed does not look like others.  Can you look at this sites twitter feed: http://fmc-shop.com/ and then mine: http://metaldetectingandotherstuffidig.us/
Mine looks completely different.  Do you know why?

Thanks,

Ray

**Comment by jono-numinix** [comment]
Hello -

Yes because they modified the template with a different Twitter plugin.

Thanks!

**Comment by Ramon-T** [comment]
Ok, thank you.

Ray
