### ISSUE TITLE
Installing Tableau on latest version of zencart

### ISSUE THREAD

**Issue by sickbuoy** [numinix/tableau#11]
I have just done a fresh install of zencart and ftp'd the latest version of the tableau template. Have done this twice and each time I can log into admin section and select the template. Once selected I click the configuration option but nothing happens. Subsequently the admin stops working. I get a message 'WARNING: An Error occurred, please refresh the page and try again.'. refresh does nothing. If you look at the actual site it does work though is in maintenance mode. Does the latest template work with the latest version of zencart?

**Comment by jefflew** [comment]
What error do you see in the /logs/ folder at the time of the warning?

**Comment by sickbuoy** [comment]
[18-Mar-2015 21:15:24 Europe/London] PHP Fatal error:  1050:Table 'zc_hide_categories' already exists ::
 RENAME TABLE hide_categories TO zc_hide_categories ==> (as called by) /home/bikeporn/public_html/thebrokenspoke.co.uk/shop/ADMINNAMEREMOVED/includes/installers/tableau/1_3_2.php on line 3 
 <== in /home/bikeporn/public_html/thebrokenspoke.co.uk/shop/includes/classes/db/mysql/query_factory.php on line 155

**Comment by sickbuoy** [comment]
On a separate note Jeff could you have a quick look at Ticket #601400 on the numinix site and give me an idea how quickly you can do the upgrade? I guess I just go through the payment option and select upgrade?

**Comment by jono-numinix** [comment]
We just released a new version of Tableau that should fix this bug. Please download the latest version and view the change log to see what files need to be modified on your server. Also, please let us know if you continue to have issues. Thanks!
