### ISSUE TITLE
translate italian

### ISSUE THREAD

**Issue by pacopardo** [numinix/tableau#12]
Hi, I'm Italian and I'm installing the theme 1.4.1 on zen cart 1.5.4. I have to translate all written, in addition to creating the file italian to includes/languages/tableau and perform all translations which other files should be changed? Thank you.
Roberto

**Comment by jefflew** [comment]
Yes, that is correct.  You would translate the files in the English folder
and copy and core files to the italian/tableau equivalent in order to
override the default.

**Comment by pacopardo** [comment]
Thank you.
