### ISSUE TITLE
minification and numinix disk cache

### ISSUE THREAD

**Issue by simon3215** [numinix/tableau#14]
i have noticed if i enable the css minification in zencart, the responsive design for mobile breaks, also if i enable the numinix disk cache this duplicates my logo beneath its self covering the menu and duplicates the shopping cart icon and search box to be positioned next to the duplicated logo any ideas ?

**Comment by jefflew** [comment]
Have you modified the css and html in the template?

**Comment by simon3215** [comment]
iv not edited css or html thorugh ftp .... only edited design on the configure in template selection (zencart) was only wanting to enable minification and cache for seo

**Comment by simon3215** [comment]
javascript minify = true without any problems

**Comment by jefflew** [comment]
Have any other plugins been installed?

**Comment by simon3215** [comment]
i have installed testimonial manager, not installed anything that required merges or modifications that i know of

**Comment by simon3215** [comment]
it seems to be when i add mnore than one product, if there is only one product then when the category is clicked on it will go straight to the product page, if i add any more than one product o get nothing showing

**Comment by jefflew** [comment]
What is your error you get in the logs when that happens?  Error logs
output to /logs/ in your store root.

On Thu, Apr 30, 2015 at 2:35 AM, simon3215 <notifications@github.com> wrote:

> it seems to be when i add mnore than one product, if there is only one
> product then when the category is clicked on it will go straight to the
> product page, if i add any more than one product o get nothing showing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/tableau/issues/14#issuecomment-97721277>.
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>
