### ISSUE TITLE
Advanced search results page goes blank

### ISSUE THREAD

**Issue by jurga23** [numinix/tableau#15]
I have installed the latest tableau (zen cart 1.5.4): all seems fine except the advanced search page. When I write down a keyword that is unknown, the advanced search results page goes blank from "Categories" to the very end of the page, even the footer information disappears. 
- I tried switching to the Classic zen cart template and it works fine. 
- I tried comparing the respective advanced search files between the two templates, Classic and Tableau, and couldn't spot anything strange. 
![advanced search results page blank](https://cloud.githubusercontent.com/assets/12159831/7380152/3172ee08-edfa-11e4-8068-a7ef284d6f54.JPG)

Where's the clue, in your opinion? 
Any idea, advice or tip is very very welcome. 
Thanks in advance!

**Comment by jefflew** [comment]
Hello,

Please check your /logs/ directory for any resulting error messages.  That will point your developer to the source of the issue.

**Comment by jono-numinix** [comment]
Hello - 

We looked into the issue and saw that this is a bug in the template. Thanks for calling it to our attention. We will be working on this for the next release.

**Comment by jono-numinix** [comment]
Hello -

We just released a patch that should fix the issue you are having. It is in version 1.4.4. Please let us know if that solves your problem. 

Just to let you know we plan to make this page look better and more functional later this week.

Thanks!

**Comment by jurga23** [comment]
Hello and thank you for a prompt support! I will check it out right away. 
And compliments for the work you are doing!

Best, 

Jurgita Po.Alessi
www.bastart.it
