### ISSUE TITLE
Uploaded and now Admin is not working

### ISSUE THREAD

**Issue by outeredge2** [numinix/tableau#18]
Last night I downloaded from your site the Tableau Responsive Template. I made the changes to the outline 2 file names to my store admin name and then uploaded them to the store root. When i did this, it uploaded fine, however now I have lost access to my admin site. I put in the URL for the admin site and get a blank page. I have no way to access anything on the back end now. How do I reactivate my Admin section? 

I believe my issue was with naming YOUR_CATALOG file. I think I named it my store Admin name....

Not sure if this can be corrected.

**Comment by jefflew** [comment]
If you did that you would have uploaded the files that go in the catalog side of your website into your admin.  You'll also have an admin folder inside of your admin folder.  The root of the package is the root of your store and the YOUR_ADMIN folder is the custom admin folder.

To fix it you'll need to manually delete all of the files that were uploaded or restore your file system to a back-up.

**Comment by outeredge2** [comment]
So will simply deleting the old files make it work correctly again or will that screw it up more?

I am currently on 1.39 and plan to upgrade to 1.54 so would I be better off doing a database back up and then starting from scratch and reload everything?

**Comment by jefflew** [comment]
That will depend on how you plan to do the upgrade.  If you are upgrading
by reinstalling all plugins and have no other modifications to your site,
it would be fine to take that route.

On Wed, Jun 24, 2015 at 1:40 PM, outeredge2 <notifications@github.com>
wrote:

> So will simply deleting the old files make it work correctly again or will
> that screw it up more?
>
> I am currently on 1.39 and plan to upgrade to 1.54 so would I be better
> off doing a database back up and then starting from scratch and reload
> everything?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/tableau/issues/18#issuecomment-115004533>.
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by outeredge2** [comment]
The only mods to the site are plug ins and then some template mods to the current template. However if I am changing to the new template it shouldn't matter. I just need to ensure my products and images work in the new system.

**Comment by outeredge2** [comment]
website is:
www.driftbuildstore.com

**Comment by jefflew** [comment]
Building on a fresh 1.5.4 is probably your safest bet then.

On Wed, Jun 24, 2015 at 1:56 PM, outeredge2 <notifications@github.com>
wrote:

> website is:
> www.driftbuildstore.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/tableau/issues/18#issuecomment-115010054>.
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by outeredge2** [comment]
without access to my admin system right now, how to do extract my product database and images etc?

**Comment by jefflew** [comment]
You can download your database through PHPMYADMIN's export feature, through
cPanel > MySQL Databases or by installing the Zen Cart database backup
plugin.

For extracting your images you can use FileManager in cPanel or FTP.

On Wed, Jun 24, 2015 at 1:59 PM, outeredge2 <notifications@github.com>
wrote:

> without access to my admin system right now, how to do extract my product
> database and images etc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/tableau/issues/18#issuecomment-115010639>.
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>
