### ISSUE TITLE
Add To Basket Button

### ISSUE THREAD

**Issue by Leon2lil** [numinix/tableau#21]
Hi 
I left a message in the forums about my add to basket button being cut off and i was to contact you here.

![add_to_cart_button](https://cloud.githubusercontent.com/assets/13746164/9194943/0e70fd86-4017-11e5-9f8c-df2a22f6e060.JPG)

Also my top logo on tablets get cut in half no matter how i resize it. Is there a way to stop that

**Comment by jefflew** [comment]
Is Tableau installed to a fresh copy of Zen Cart or did you have a previous template installed first?  It sounds like either Zen Cart is setting a width on the button or there is CSS in your template that is restricting the width.  Try using the Inspect Element function of your browser to investigate.

**Comment by Leon2lil** [comment]
It is being restricted but it was a fresh install... First and only thing still installed. Do you know what file needs to be changed.
http://prohairtherapyltd.co.uk

**Comment by jonorherrington** [comment]
@Leon2lil do you have css buttons turned on in your settings? It should be under your admin and then under configuration => layout settings.

**Comment by Leon2lil** [comment]
Hi Guys
Sorry for the late reply. I have been busy.
I can't seem to find any style sheets that are restricting it

Also i do have css buttons turned on

**Comment by jonorherrington** [comment]
Hello @Leon2lil -

Are you sure you have the latest version of tableau installed? I have done a couple of installs of Tableau this week and have not found this issue. There is something injecting the width as an inline style.

**Comment by Leon2lil** [comment]
Brand new install same problem

**Comment by Leon2lil** [comment]
Figured It Out 
This didn't change
In /includes/functions/html_output.php, you'll find a function zenCssButton($image = '', $text, $type, $sec_class = '', $parameters = '') that builds the Submit buttons.

Change line 330 from this:
$style = ' style="width: ' . $width . 'px;"';

to this:
$style = ''; // $style = ' style="width: ' . $width . 'px;"';
