### ISSUE TITLE
Large image disappears

### ISSUE THREAD

**Issue by gunghonights** [numinix/tableau#25]
I am just testing version 10 (latest on your site) of the tableau template.  I have a bug with the large images which I did not have before.  When I click on the large image the image vanishes and the large image does not pop up in the window as it does normally.  Or if it does pop up when I close it then the large image on the product page has disappeared and I cannot re look at the image and the smaller additional images do not pop up when clicked.

This issue only seems to occur in the latest version which says it has fixed image pop up issues..

**Comment by jefflew** [comment]
Can you please provide a link to a product page with the issue?

Is image handler enabled and set to resize images in your images
configuration?
