### ISSUE TITLE
Shipping estimator not working.

### ISSUE THREAD

**Issue by redsautorehab** [numinix/tableau#26]
I am using zen-cart 1.5.4, and the shipping estimator does not work, unless the customer is logged in. I am using freeshipper, ups, and usps. Freeshipper will show up as a result when a free item is in the cart, but none of the others will. As soon as I log in, the estimator works perfectly. If I switch back to the default template, it works perfectly.

**Comment by redsautorehab** [comment]
I forgot to mention the site: redsautorehab.com

**Comment by redsautorehab** [comment]
It's kind of working now. In configuration - shipping/packaging I changed the shipping estimator display to button.

That created a new problem though: in firefox, and chrome, that link only works by selecting open in new tab. In explorer, it works fine.

**Comment by redsautorehab** [comment]
Deleted lines 61-63 of tpl_modules_shipping_estimator.php
Code:

    <label class="inputLabel" for="state" id="stateLabel"><?php echo $state_field_label; ?></label>
    <?php echo zen_draw_input_field('state', $selectedState, zen_set_field_length(TABLE_ADDRESS_BOOK, 'entry_state', '40') . ' id="state"') .'&nbsp;<span class="alert" id="stText"></span>'; ?>
    <br class="clearBoth" />

That got rid of the extra blank field, but still did not allow the estimator on the shopping cart work. That did, however allow the popup shipping estimator to work. I would really like to get to the bottom of this, and get the estimator back on the shopping cart, rather than a popup window.

**Comment by jefflew** [comment]
Please note: we're moving our bug reporting system to bitbucket.org.
