### ISSUE TITLE
PHP error thrown by "constant" in tpl_modules_hp_product_carousels.php

### ISSUE THREAD

**Issue by ms1225** [numinix/tableau#27]
PHP Warning: constant(): Couldn't find constant TITLE_HOME_TAB_BEST_SELLERS in xxx/includes/templates/tableau/templates/tpl_modules_hp_product_carousels.php on line 49

**Comment by jefflew** [comment]
Make sure that you upload the modified languages files.

**Comment by jefflew** [comment]
Fixed in v1.6.13
